import Head from "next/head";
import Router from "next/router";
import classes from "./index.module.css";

export default function Home() {
  setTimeout(() => {
    Router.push("/landingsecond");
  }, 3000);
  return (
    <>
      <Head>
        <title>Habit, Have it!</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Habit, Have it" />
        <meta
          property="og:description"
          content="자신의 결심을 나누고 응원받으며 보다 알찬 한달을 보내길 바래요"
        />
        <meta
          property="og:image"
          content="{{ url_for('static', filename='image.png') }}"
        />
        <link rel="icon" href="/favicon2.ico" />
      </Head>
      <div>
        <img className={classes.letter} src="../letter.png" />
      </div>
    </>
  );
}
