import Head from "next/head";
import Router from "next/router";
import classes from "./index.module.css";

export default function Home() {
  setTimeout(() => {
    Router.push("/landingsecond");
  }, 3000);
  return (
    <>
      <Head>
        <title>Habit, Have it!</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:title" content="Habit, Have it" />
        <meta
          property="og:description"
          content="자신의 결심을 나누고 응원받으며 보다 알찬 한달을 보내길 바래요"
        />
        <meta
          property="og:image"
          content="https://i.ibb.co/GpqQGXt/2022-01-27-11-49-30.png"
        />
        <link rel="icon" href="/favicon2.ico" />
      </Head>
      <div className={classes.indexText}>
        <img className={classes.letter} src="../letter.png" loading="lazy" />
        <div>
          <p>Habit, Haveit!</p>
          <p>
            언제나 작심삼일에 그치고 마는 우리의 결심들. 그 결심을 친구들과
            공유하고 서로 응원한다면, 가능하지 않을까요?
          </p>
        </div>
      </div>
    </>
  );
}
